#!/bin/sh
# /etc/init.d/nmea_proxy

### BEGIN INIT INFO
# Provides:          nmea_proxy
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start nmea_proxy.py at boot
# Description:       A basic script to start nmea_proxy.py at boot.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting nmea_proxy"
    # run application you want to start
    /root/repos/NMEAProxy/NMEAProxy/nmea_proxy.py --tcp 2000 --uart /dev/ttyACM0 --loglevel INFO --logfile /var/log/nmea_proxy &
    ;;
  stop)
    echo "Stopping nmea_proxy"
    # kill application you want to stop
    kill -s INT `ps aux | grep 'nmea_proxy.py' | grep -v grep | awk '{print $2}'`
    ;;
  *)
    echo "Usage: /etc/init.d/nmea_proxy {start|stop}"
    exit 1
    ;;
esac

exit 0
